### ISSUE TITLE
500 Internal Server Error when login failed.

### ISSUE THREAD

**Issue by JamieSharpe** [josh-perry/literallyjosh.com#1]
If the login failed then user is not given a redirect page, causing an internal server error.

[Django Login Example](https://docs.djangoproject.com/en/1.9/topics/auth/default/#django.contrib.auth.login).

Provide a fallback [here](https://github.com/josh-perry/literallyjosh.com/blob/649f64e885db82bbff4f432f3ff1d3092d9cf6e3/blog/views.py#L24
) in your code.

**Comment by josh-perry** [comment]
Fixed in 1486fe7e97fa6f21b8b0e1e52a2e7c67de288152

**Comment by JamieSharpe** [comment]
Thanks!
